from report import *

print("running processes")
print(get_process_num())
print("\ncpu info")
print(get_cpu_info())
print(get_cpu_core())
print(get_cpu_load())
print(get_cpu_temp())
print("\nip")
print(get_ipv4())
print(get_ipv6())
print("\nconnection")
print(get_connections())
print("\nuptime")
print(get_uptime())
print("\nsystem version")
print(get_sys_version())
print("\nMem & Disk")
print(get_mem_info())
print(get_disk_info())
